---
version: "3.9"

services:
  serve:
    image: "httpm"
    build:
      context: ./
    depends_on:
      - monitor
    command: "serve"
    ports:
      - "${HTTPM_HTTP_PORT}:${HTTPM_HTTP_PORT}"
    env_file:
      - .env

  monitor:
    image: "httpm"
    build:
      context: ./
    depends_on:
      - database
    command: "monitor --migrate-first"
    env_file:
      - .env


  database:
    image: "mongo:6.0.1"
    ports:
      - "${HTTPM_DATABASE__PORT}:${HTTPM_DATABASE__PORT}"
    volumes:
      - "httpm-data:/data/db"
    env_file:
      - .env

volumes:
    httpm-data: