name: Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build-and-test:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19

    - name: Build
      run: go build -o httpm -v

    - name: Start MongoDB
      uses: supercharge/mongodb-github-action@1.8.0
      with:
        mongodb-version: 6.0.1

    - name: Run monitoring module
      run: ./httpm monitor --migrate-first &

    - name: Run http server
      run: ./httpm serve &
      env:
        HTTPM_HTTP_PORT: 3000

    - name: Test Postman collection
      uses: matt-ball/newman-action@master
      with:
        collection: test/http-monitoring.postman_collection.json
        iterationData: test/api_test_data.json
        timeout: 20000
        delayRequest: 100